FROM python:3.10

WORKDIR /src

COPY . /src/

RUN pip install --no-cache-dir -r /src/requirements.txt

CMD ["fastapi", "run", "api.py", "--port", "80", "--proxy-headers"]

# docker build --tag park-sync-backend .
# docker run -d --name park-sync-backend --publish 5004:80 park-sync-backend